### ISSUE TITLE
feat: Implement dynamic version management to eliminate manual updates

### ISSUE THREAD

**Issue by doughayden** [doughayden/answer-app#10]
## Feature Request

Implement automatic version management to eliminate the need for manual version updates in `pyproject.toml` and other files throughout the codebase.

## Level of Effort: 🔥 Large (3-5 days)
- **Research and design**: 1 day to evaluate version management approaches
- **Implementation**: 2-3 days for setuptools_scm integration and configuration
- **Testing and validation**: 1 day for comprehensive testing across environments

## Current Problem

The project version is currently hard-coded in multiple locations and requires manual updates:

**pyproject.toml:**
```toml
[project]
version = "0.2.0"
```

**Manual update locations tracked by semantic-release:**
```toml
[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
version_variables = [
    "CLAUDE.md:0.2.0",
    "README.md:version-0.2.0",
]
```

**Issues with current approach:**
- Manual version updates are error-prone and easy to forget
- Multiple files must be kept in sync manually
- Version mismatches can occur between files
- Requires developer intervention for every release

### Option 1: Dynamic Version from Git Tags (Recommended)

Use `setuptools_scm` or similar to derive version dynamically from Git tags:

**Benefits:**
- Zero manual version management
- Single source of truth (Git tags)
- Automatic dev version increments
- Integrates seamlessly with semantic-release

**Implementation:**
```toml
[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "release-branch-semver"
```

### Option 2: Version File Generation

Generate version information at build time from semantic-release:

**Implementation:**
```toml
[tool.semantic_release]
version_toml = []  # Remove manual version tracking
build_command = "python scripts/generate_version.py && poetry build"
```

### Option 3: Import-time Version Detection

Use `importlib.metadata` to read version at runtime:

```python
from importlib.metadata import version
__version__ = version("answer-app")
```

## Expected Benefits

1. **Zero maintenance**: No manual version updates required
2. **Consistency**: Version automatically synced across all files
3. **Developer experience**: Simplified release process
4. **Reliability**: Eliminates version mismatch errors
5. **CI/CD friendly**: Seamless automation support

### Files that reference version:
- `pyproject.toml` (project.version)
- `CLAUDE.md` (version references)
- `README.md` (badge and version references)
- Documentation files
- Docker build tags in development guide

### Integration with semantic-release:
- Update semantic-release config to work with dynamic versioning
- Ensure GitHub releases still get proper version tags
- Maintain changelog generation functionality

### Backward compatibility:
- Consider migration path from current hard-coded approach
- Ensure existing tooling continues to work

## Acceptance Criteria

- [ ] Version is derived automatically from Git tags or build process
- [ ] No manual version updates required in any files
- [ ] All version references stay synchronized automatically
- [ ] Semantic-release continues to work correctly
- [ ] Documentation reflects current version dynamically
- [ ] Local development and CI/CD workflows unchanged
- [ ] Migration guide provided for switching approaches

## Priority

**Medium** - This is a quality-of-life improvement that will reduce maintenance overhead and eliminate a common source of errors in the release process.

## Related Issues

- #9 - Poetry command not found during semantic-release (may be resolved as part of this work)
