### ISSUE TITLE
feat: Add Claude Code GitHub Actions for automated PR code reviews

### ISSUE THREAD

**Issue by doughayden** [doughayden/answer-app#22]
## What
Add Claude Code GitHub Actions integration to provide AI-powered code reviews on pull requests and automate feature implementation from issues.

## Why
- Improve code quality through AI-powered reviews
- Accelerate development by automating feature implementation from issues
- Maintain consistent code standards via CLAUDE.md configuration
- Reduce manual review overhead for routine changes

### 1. Install Claude GitHub App
- Visit GitHub repository settings
- Navigate to Integrations → GitHub Apps
- Install the Claude GitHub app with appropriate permissions

### 2. Add Anthropic API Key
- Go to repository Settings → Secrets and variables → Actions
- Add new repository secret: `ANTHROPIC_API_KEY`
- Obtain API key from Anthropic Console (https://console.anthropic.com)

### 3. Create Workflow File
Create `.github/workflows/claude-code.yml`:

```yaml
name: Claude Code Actions
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  claude-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anthropics/claude-code-action@v1
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

#### Turn Issues into PRs
- Comment on any issue with: `@claude implement this`
- Claude will analyze the issue and create a pull request with implementation

#### Get Code Reviews
- Claude automatically reviews pull requests
- Provides feedback on code quality, potential bugs, and improvements
- Respects project patterns defined in `CLAUDE.md`

#### Request Specific Help
- Comment `@claude fix the bug in [file]` on issues
- Comment `@claude review this change` on PRs for detailed analysis

### 5. Configuration via CLAUDE.md
Claude respects our existing `CLAUDE.md` configuration including:
- Project overview and tech stack
- Code quality standards
- Testing requirements
- Architecture patterns

### 6. Best Practices
- Review Claude's suggestions before merging
- Use GitHub branch protection rules
- Set appropriate workflow timeouts
- Monitor GitHub Actions usage

## Priority
Medium - Enhances development workflow and code quality

## Level of Effort
Low - Primarily configuration and setup work

## Related Documentation
- [Claude Code GitHub Actions](https://docs.anthropic.com/en/docs/claude-code/github-actions)
- Existing `CLAUDE.md` provides project context for Claude

🤖 Generated with [Claude Code](https://claude.ai/code)
