### ISSUE TITLE
fix: semantic-release Git push fails with branch protection

### ISSUE THREAD

**Issue by doughayden** [doughayden/answer-app#23]
## Problem Description

After resolving the Poetry command not found issue (#9), semantic-release now successfully builds distributions but fails during the Git push step with:

```
Failed to push branch (main) to remote
```

## Context

- **Parent Issue**: #9 (Poetry command not found - now resolved)
- **Workflow**: `.github/workflows/release.yml`
- **Step**: `Python Semantic Release` - git push phase
- **Branch**: `main` (protected branch)

## Root Cause Analysis

The error suggests semantic-release cannot push to the `main` branch, likely due to:

1. **Branch protection rules** preventing direct pushes
2. **Insufficient permissions** for the `GITHUB_TOKEN` 
3. **Missing configuration** for protected branch handling

## Current Configuration

**GitHub Actions workflow:**
```yaml
- name: Python Semantic Release
  uses: python-semantic-release/python-semantic-release@v9.15.0
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    root_options: "-vv"
```

**Semantic-release config:**
```toml
[tool.semantic_release]
# ... other config ...
```

### Option 1: Configure semantic-release for protected branches
Add push configuration to handle branch protection:
```toml
[tool.semantic_release]
push = false  # Disable automatic push
# or configure bypass settings
```

### Option 2: Update GitHub token permissions
Ensure workflow has sufficient permissions:
```yaml
permissions:
  contents: write
  pull-requests: write
```

### Option 3: Use PAT instead of GITHUB_TOKEN
Create Personal Access Token with admin permissions if needed.

## Expected Outcome

Semantic-release should successfully:
- Build distributions ✅ (working after #9 fix)
- Create version tags and commits
- Push changes to main branch
- Create GitHub releases

## Related

- Resolves remaining workflow failure from #9
- Part of automated release pipeline improvements

## Priority

**Medium** - Blocks automated releases but Poetry build issue is resolved.
