### ISSUE TITLE
fix: Poetry command not found during semantic-release in GitHub Actions

### ISSUE THREAD

**Issue by doughayden** [doughayden/answer-app#9]
## Problem Description

The GitHub Actions release workflow is failing during the semantic-release step with the error:
```
bash: line 1: poetry: command not found
```

This occurs specifically during the `poetry build` command execution within the semantic-release Docker container, despite Poetry being available in the runner environment.

## Level of Effort: 🟡 Medium (1-2 days)
- **Investigation and testing**: 0.5-1 day to test different solutions
- **Implementation**: 0.5-1 day to implement and validate the fix

## Context

- **Workflow**: `.github/workflows/release.yml`
- **Job**: `release` (runs only on pushes to `main` branch)
- **Step**: `semantic-release` execution
- **Error location**: During `poetry build` command in semantic-release container

## Root Cause Analysis

The issue stems from semantic-release running inside a Docker container that doesn't have Poetry installed or accessible, even though:
1. Poetry is installed in the GitHub Actions runner environment
2. Poetry PATH has been added via: `echo "$HOME/.local/bin" >> $GITHUB_PATH`
3. The semantic-release configuration specifies: `build_command = "poetry build"`

## Current Configuration

**pyproject.toml semantic-release config:**
```toml
[tool.semantic_release]
build_command = "poetry build"
dist_path = "dist/"
upload_to_pypi = false
upload_to_release = true
```

**Workflow PATH fix (already attempted):**
```yaml
- name: Add poetry to PATH
  run: echo "$HOME/.local/bin" >> $GITHUB_PATH
```

### Option 1: Install Poetry in semantic-release container
Modify the workflow to ensure Poetry is available in the semantic-release execution context:
```yaml
- name: Install Poetry in container
  run: pip install poetry
- name: Semantic Release
  run: semantic-release version
```

### Option 2: Use pip build instead of Poetry
Update semantic-release configuration to use pip/build instead:
```toml
[tool.semantic_release]
build_command = "python -m build"
```

### Option 3: Pre-build artifacts
Build the distribution before semantic-release and update config:
```yaml
- name: Build distribution
  run: poetry build
- name: Semantic Release
  run: semantic-release version
```
```toml
[tool.semantic_release]
build_command = ""  # or remove this line
```

### Option 4: Custom semantic-release Docker image
Use a Docker image that includes Poetry or build a custom one.

## Expected Outcome

The release workflow should complete successfully without Poetry command errors, enabling:
- Automated version bumping based on conventional commits
- Changelog generation
- GitHub release creation with distribution artifacts

## Priority

**High** - This blocks automated releases and version management for the project.

**Comment by doughayden** [comment]
## ✅ Poetry Command Not Found Issue - RESOLVED

The original "poetry: command not found" error has been **successfully fixed** using the proven approach from [this guide](https://mestrak.com/blog/semantic-release-with-python-poetry-github-actions-20nn).

### Solution Implemented

**Modified `pyproject.toml`:**
```toml
[tool.semantic_release]
build_command = "pip install poetry && poetry build"
```

**Why this works:**
- Poetry is installed within the semantic-release Docker container
- Avoids Docker isolation issues between GitHub Actions runner and semantic-release container
- Maintains consistent Poetry usage throughout the pipeline

### Verification

**Before fix:**
```
CalledProcessError: Command '['bash', '-c', 'poetry build']' returned non-zero exit status 127
```

**After fix:**
```
🛠 Running build command: pip install poetry && poetry build
Collecting poetry
  Downloading poetry-2.1.3-py3-none-any.whl.metadata (7.1 kB)
[... successful Poetry installation and build ...]
```

### Documentation

Added comprehensive documentation in [`docs/development/version-management.md`](../blob/main/docs/development/version-management.md#poetry-integration-strategy) covering:
- Docker container isolation challenges
- Step-by-step solution explanation
- Alternative approaches considered
- Troubleshooting guide

### New Issue Discovered

The workflow now progresses past the Poetry build but encounters a new **Git push error**: `Failed to push branch (main) to remote`. This is tracked in issue #23.

**Status: Issue #9 is resolved** ✅
